### ISSUE TITLE
Mock server not handling routes queries?

### ISSUE THREAD

**Issue by salty-horse** [elad661/curlbus#16]
I have executed `update_feed.sh` to fill my local database.

After making a call to `/10000`, curlbus fails on:
```
Traceback (most recent call last):
  File "/home/ori/.virtualenvs/curlbus/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 378, in start
    resp = await self._request_handler(request)
  File "/home/ori/.virtualenvs/curlbus/lib/python3.6/site-packages/aiohttp/web_app.py", line 341, in _handle
    resp = await handler(request)
  File "/home/ori/.virtualenvs/curlbus/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/home/ori/.virtualenvs/curlbus/lib/python3.6/site-packages/gino/ext/aiohttp.py", line 109, in _middleware
    return await handler(request)
  File "/home/ori/devel/curlbus/curlbus/server.py", line 122, in handle_station
    response = await client.request([stop_code])
  File "/home/ori/devel/curlbus/curlbus/siri.py", line 192, in request
    response = SIRIResponse(text, group, self.verbose)
  File "/home/ori/devel/curlbus/curlbus/siri.py", line 104, in __init__
    for delivery in _listify(answer['ns3:StopMonitoringDelivery']):
KeyError: 'ns3:StopMonitoringDelivery'
```

I printed `answer` on the line where it fails:
```
OrderedDict([('ns3:ResponseTimestamp', '2018-06-16T20:04:29.187+03:00'),
             ('ns3:ProducerRef', 'ISR Siri Server (141.11)'),
             ('ns3:ResponseMessageIdentifier', '16503786'),
             ('ns3:RequestMessageRef', 'user id from MoT:1529168696.3143766'),
             ('ns3:Status', 'false'),
             ('ns3:ErrorCondition',
              OrderedDict([('ns3:OtherError',
                            OrderedDict([('ns3:ErrorText', '720')])),
                           ('ns3:Description',
                            'User authentication failed for user id from MoT '
                            'from MY_IP_IS_HERE')]))])
```

BTW, why is my internet-facing IP address in the answer, instead of the localhost address from which I made the request?

**Comment by elad661** [comment]
Because you're not connecting to the mock server! you're connecting to the real live MoT server :)

You should change your configuration file to connect to localhost instead

**Comment by elad661** [comment]
The default configuration example assumes (maybe wrongfully) that you have access to the MoT API

**Comment by salty-horse** [comment]
Doh, thanks. Finally got it to work! :)

I missed the "pointing your config file to it" instructions. I think `README.md` can be a bit more detailed in which setting it wants me to edit.
