### ISSUE TITLE
asyncpg.exceptions.UndefinedTableError: relation "stops" does not exist

### ISSUE THREAD

**Issue by guysoft** [elad661/curlbus#26]
curl localhost:8081/1 output:

```curlbus    | ======== Running on http://0.0.0.0:80 ========
curlbus    | (Press CTRL+C to quit)
curlbus    | Error handling request
curlbus    | Traceback (most recent call last):
curlbus    |   File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_protocol.py", line 433, in _handle_request
curlbus    |     resp = await request_handler(request)
curlbus    |   File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_app.py", line 504, in _handle
curlbus    |     resp = await handler(request)
curlbus    |   File "/usr/local/lib/python3.10/dist-packages/aiohttp/web_middlewares.py", line 117, in impl
curlbus    |     return await handler(request)
curlbus    |   File "/usr/local/lib/python3.10/dist-packages/gino_aiohttp.py", line 114, in _middleware
curlbus    |     return await handler(request)
curlbus    |   File "/curlbus/curlbus/server.py", line 149, in handle_station
curlbus    |     stop_info = await get_stop_info(db, stop_code)
curlbus    |   File "/usr/local/lib/python3.10/dist-packages/aiocache/decorators.py", line 109, in wrapper
curlbus    |     return await self.decorator(f, *args, **kwargs)
curlbus    |   File "/usr/local/lib/python3.10/dist-packages/aiocache/decorators.py", line 124, in decorator
curlbus    |     result = await f(*args, **kwargs)
curlbus    |   File "/curlbus/curlbus/gtfs/utils.py", line 126, in get_stop_info
curlbus    |     stop = await query.gino.first()
curlbus    |   File "/usr/local/lib/python3.10/dist-packages/gino/api.py", line 137, in first
curlbus    |     return await self._query.bind.first(self._query, *multiparams, **params)
curlbus    |   File "/usr/local/lib/python3.10/dist-packages/gino/engine.py", line 328, in first
curlbus    |     return await result.execute(one=True)
curlbus    |   File "/usr/local/lib/python3.10/dist-packages/gino/dialects/base.py", line 214, in execute
curlbus    |     rows = await cursor.async_execute(
curlbus    |   File "/usr/local/lib/python3.10/dist-packages/gino/dialects/asyncpg.py", line 184, in async_execute
curlbus    |     result, stmt = await getattr(conn, "_do_execute")(query, executor, timeout)
curlbus    |   File "/usr/local/lib/python3.10/dist-packages/asyncpg/connection.py", line 1711, in _do_execute
curlbus    |     stmt = await self._get_statement(
curlbus    |   File "/usr/local/lib/python3.10/dist-packages/asyncpg/connection.py", line 397, in _get_statement
curlbus    |     statement = await self._protocol.prepare(
curlbus    |   File "asyncpg/protocol/protocol.pyx", line 168, in prepare
curlbus    | asyncpg.exceptions.UndefinedTableError: relation "stops" does not exist

```

postgres 14

**Comment by guysoft** [comment]
My bad, forgot to run:
```
sudo docker exec -it curlbus /curlbus/update_feed.sh
sudo docker exec -it curlbus /curlbus/load_cities.py -c /curlbus/config.ini
```
