### ISSUE TITLE
Missing packages in requirements.txt - psycopg2?

### ISSUE THREAD

**Issue by salty-horse** [elad661/curlbus#6]
Running the mock server failed due to missing `psycopg2`.

After installing `psycopg2==2.7.4` it failed with:
```
  File "/lib/python3.6/site-packages/gino/strategies.py", line 42, in create
    pool = await dialect.init_pool(u, loop)
AttributeError: 'PGDialect_psycopg2' object has no attribute 'init_pool'
```

Is it because I have the wrong version of some packages?

**Comment by elad661** [comment]
The mock server doesn't use `psycopg2` at all. You need `asyncpg==0.15.0` which should've been pulled by gino when installed via pip.

To test, I've set up a virtualenv and ran
`bin/pip3 install -r curlbus/requirements.txt`

After doing that all required packaged were pulled and the mock server started successfully.

If it helps in any way, this is the output of `bin/pip3 freeze` in the virtualenv:

```
aiocache==0.9.1
aiohttp==3.3.0
ansi2html==1.4.2
async-timeout==3.0.0
asyncpg==0.15.0
attrs==18.1.0
chardet==3.0.4
docopt==0.6.2
gino==0.7.3
idna==2.6
idna-ssl==1.0.1
multidict==4.3.1
python-dateutil==2.7.3
six==1.11.0
SQLAlchemy==1.2.7
xmltodict==0.11.0
yarl==1.2.4
```

**Comment by salty-horse** [comment]
This is the error I'm getting without `psycopg2`:
```
Traceback (most recent call last):
  File "./mock_siri_server.py", line 188, in <module>
    main()
  File "./mock_siri_server.py", line 184, in main
    server.run(port)
  File "./mock_siri_server.py", line 136, in run
    web.run_app(self._app, port=port)
  File "/lib/python3.6/site-packages/aiohttp/web.py", line 60, in run_app
    loop.run_until_complete(runner.setup())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/lib/python3.6/site-packages/aiohttp/web_runner.py", line 178, in setup
    self._server = await self._make_server()
  File "/lib/python3.6/site-packages/aiohttp/web_runner.py", line 275, in _make_server
    await self._app.startup()
  File "/lib/python3.6/site-packages/aiohttp/web_app.py", line 278, in startup
    await self.on_startup.send(self)
  File "/lib/python3.6/site-packages/aiohttp/signals.py", line 35, in send
    await receiver(*args, **kwargs)
  File "/lib/python3.6/site-packages/gino/ext/aiohttp.py", line 141, in before_server_start
    loop=app_.loop,
  File "/lib/python3.6/site-packages/gino/ext/aiohttp.py", line 161, in set_bind
    return await super().set_bind(bind, loop=loop, **kwargs)
  File "/lib/python3.6/site-packages/gino/api.py", line 386, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "/lib/python3.6/site-packages/gino/strategies.py", line 38, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/lib/python3.6/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 584, in dbapi
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
```

`pip freeze` output:
```
$ pip freeze
aiocache==0.9.1
aiohttp==3.3.0
ansi2html==1.4.2
async-timeout==3.0.0
asyncpg==0.15.0
attrs==18.1.0
chardet==3.0.4
docopt==0.6.2
gino==0.7.3
idna==2.6
idna-ssl==1.0.1
multidict==4.3.1
pkg-resources==0.0.0
python-dateutil==2.7.3
six==1.11.0
SQLAlchemy==1.2.7
xmltodict==0.11.0
yarl==1.2.4
```

It's possible one of us has local packages installed that leak into the virtualenv.

**Comment by elad661** [comment]
Yeah, that's probably a problem on my end. I tried installing it on a fresh CentOS 7 installation and I'm getting a slightly different error around the same place,
```
Traceback (most recent call last):
  File "mock_siri_server.py", line 188, in <module>
    main()
  File "mock_siri_server.py", line 184, in main
    server.run(port)
  File "mock_siri_server.py", line 136, in run
    web.run_app(self._app, port=port)
  File "/home/test/.local/lib/python3.6/site-packages/aiohttp/web.py", line 60, in run_app
    loop.run_until_complete(runner.setup())
  File "/usr/lib64/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/test/.local/lib/python3.6/site-packages/aiohttp/web_runner.py", line 178, in setup
    self._server = await self._make_server()
  File "/home/test/.local/lib/python3.6/site-packages/aiohttp/web_runner.py", line 275, in _make_server
    await self._app.startup()
  File "/home/test/.local/lib/python3.6/site-packages/aiohttp/web_app.py", line 278, in startup
    await self.on_startup.send(self)
  File "/home/test/.local/lib/python3.6/site-packages/aiohttp/signals.py", line 35, in send
    await receiver(*args, **kwargs)
  File "/home/test/.local/lib/python3.6/site-packages/gino/ext/aiohttp.py", line 141, in before_server_start
    loop=app_.loop,
  File "/home/test/.local/lib/python3.6/site-packages/gino/ext/aiohttp.py", line 161, in set_bind
    return await super().set_bind(bind, loop=loop, **kwargs)
  File "/home/test/.local/lib/python3.6/site-packages/gino/api.py", line 386, in set_bind
    bind = await create_engine(bind, loop=loop, **kwargs)
  File "/home/test/.local/lib/python3.6/site-packages/gino/strategies.py", line 22, in create
    dialect_cls = u.get_dialect()
  File "/home/test/.local/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 171, in get_dialect
    entrypoint = self._get_entrypoint()
  File "/home/test/.local/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 156, in _get_entrypoint
    cls = registry.load(name)
  File "/home/test/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 221, in load
    (self.group, name))
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:asyncpg
```

I'll look into it soon.

**Comment by elad661** [comment]
One issue I found is that the example configuration incorrectly contained the dialect, which is not the way it should be according to the [gino documentation](https://python-gino.readthedocs.io/en/latest/tutorial.html#get-connected).

I can't find any other issue though. Can't get it to work on CentOS 7 (with python 3.6.3), but it does work on my two Fedora machines with Python 3.6.5...

**Comment by elad661** [comment]
@salty-horse Fixed! turns out older setuptools is broken and breaks adding custom dialects to SQLAlchemy, which gino (the library I use for async SQLAlchemy) requires. I've added `setuptools >= 39.2.0` to requirements.txt - and my guess is that if you install it (and don't mention `psycopg2` in your connection string), curlbus will work.

**Comment by salty-horse** [comment]
Confirmed fixed. Thanks!
